export * as authApi from './modules/auth'
export * as categoriesApi from './modules/categories'
export * as recipesApi from './modules/recipes'
export * as tagsApi from './modules/tag'
export * as usersApi from './modules/user'
export * as favApi from './modules/fav'
export * as profileApi from './modules/profile'